Controllers films users
Kazantsevyury/java-filmorate pull request #4
Opened 2023-09-01 14:22 UTC by Kazantsevyury

2023-09-02 10:43 UTC, PolnySkvorets commented on checkstyle.xml
Зачем удалены эти файлы?

2023-09-02 10:46 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/model/HomeController.java
> +public class HomeController {
Этого контроллера нет в требованиях

2023-09-02 10:46 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final String name;
не забывай отступы

2023-09-02 10:49 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PostMapping("/save")
Не нужно в пути прописывать названия этих методов, оставь просто postMapping,  также сделай и с методами ниже

2023-09-02 10:54 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping("/save")
Отступы и аналогично замечаниям в UserController

2023-09-02 10:55 UTC, PolnySkvorets requested changes
привет! Оставил несколько замечаний. Есть отход от требований, посмотри, но исправлять немного

2023-09-02 20:44 UTC, Kazantsevyury commented on src/main/java/ru/yandex/practicum/filmorate/model/HomeController.java
> +public class HomeController {
Убрал

2023-09-02 21:10 UTC, Kazantsevyury commented on checkstyle.xml
Я попытался восстановить эти файлы, но почему то у меня не получилось. В итоге просто скачал с github и вручную засунул в проект.
Подскажи пожалуйста, что не так ? 

 ~/dev/java-filmorate (controllers-films-users)
$ git checkout -- lombok.config
error: pathspec 'lombok.config' did not match any file(s) known to git

Так же попробовал так 
~/dev/java-filmorate (controllers-films-users)
$ git add lombok.config
fatal: pathspec 'lombok.config' did not match any files

2023-09-02 22:53 UTC, Kazantsevyury commented
Честно, я не понял, как создать еще один pull  request, на ту же ветку.
Исправил твои замечания но теперь тесты не проходит

2023-09-03 20:10 UTC, PolnySkvorets commented
не нужно создавать новый ПР. Простоев свою ветку пушишь изменения. ПР  - один

2023-09-03 20:28 UTC, PolnySkvorets requested changes
Посмотри, попробуй написать наставнику. Похоже, что в мастере были файлы, которые попали в мр, но их там не должно быть, вроде  maven-wrapper.jar .gitignore. Похоже действительно нуно будет мр заново создать или сделать ребейз от мастера. Поговори с наставником, как решить эту проблему

2023-09-07 00:30 UTC, Kazantsevyury commented
С файлами вроде разобрался. 
Но не могу понять, что ему не нравится теперь

2023-09-11 23:57 UTC, Kazantsevyury commented
У меня не получилось использовать свою валидацию. Почему то она не работала. Даже при отправлении только id - создавался класс, с полями null. По этому пришлось все переписать. Если ты смог бы подсказать - по какой причине может не работать валидация ? зависимость была прописана.

2023-09-12 11:29 UTC, PolnySkvorets approved these changes
Теперь всё поправлено, отлично

2023-09-13 02:20 UTC, merged