feat: Create FilmStorage and UserStorage interfaces
Kazantsevyury/java-filmorate pull request #5
Opened 2023-09-17 23:41 UTC by Kazantsevyury

- Define methods for adding, deleting, and modifying objects

feat: Implement InMemoryFilmStorage and InMemoryUserStorage classes

- Implement the new interfaces
- Move storage, update, and retrieval logic to these classes

feat: Introduce UserService and FilmService

- UserService for user-related operations
- FilmService for film-related operations

refactor: Refactor FilmController and UserController for REST compliance

test: Add unit tests for FilmController and UserController

2023-09-18 16:21 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Посмотри в других местах тоже. Если ты добавляешь аннотацию @RequiredArgsConstructor (или любой другой конструктор), то у тебя по умолчанию пудет внедрение зависимостей в этот конструктор без аннотации @Autowired . Так что здесь ты можешь её удалить

2023-09-18 16:24 UTC, PolnySkvorets reviewed
Привет! Посмотри замечания по использованию аннотаций

2023-09-20 03:36 UTC, Kazantsevyury commented
Привет, я не могу понять. Какая логика где должна быть . 


Насколько я понял , то все проверки должны быть как можно выше, т.е в нашем случае в  контроллере, а в сервисы  и хранилище попадают уже чистые данные. 

Но в задание просили спустить логику из контроллеров ниже , что мне кажется не очень логи- зачем делать к примеру вадидацию при сохранении , если это можно сделать ещё в самом начале и не пустить опасные данные дальше .

2023-11-01 12:29 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        findId(userId, friendId);
Лучше не делать такой метод. Он выглядит непонятно - название "найти Id", но передаётся два параметра. Нужно создать метод, который по отдельности будет проверять эти айдишники

2023-11-01 12:30 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.retrieveUserMap().get(userId).getIdFriends().add(friendId);
Здесь лучше искать по айди, не всех пользователей доставать. Слишком тяжёлый запрос получается, при чём вызывается дважды.

2023-11-01 12:53 UTC, PolnySkvorets requested changes
Привет! В целом всё хорошо. Оставил немного замечаний

2023-11-02 07:51 UTC, PolnySkvorets commented
"Привет, я не могу понять. Какая логика где должна быть .

Насколько я понял , то все проверки должны быть как можно выше, т.е в нашем случае в контроллере, а в сервисы и хранилище попадают уже чистые данные.

Но в задание просили спустить логику из контроллеров ниже , что мне кажется не очень логи- зачем делать к примеру вадидацию при сохранении , если это можно сделать ещё в самом начале и не пустить опасные данные дальше ."

Пропустил этот вопрос. Есть разные проверки: например формат данных, или их отсутствие на входе можно проверить в контроллере аннотациями. НО! В репозиториях валидации не надо оставлять. Они должны быть в сервисах - там уже специфично должо зависеть от ситуации. Потому что одному потреителю данных - окей получить пустой результат, а другому нет, и там надо выкинуть  исключение

2023-11-02 21:12 UTC, merged